<#
.SYNOPSIS
    Builds the single-file unknowntweaks.ps1 that the one-liner downloads.
.DESCRIPTION
    Concatenates, in order:
      1. a header + the shared $sync hashtable and build constants
      2. every function under functions/ (private first, then public)
      3. every config/*.json embedded as a single-quoted here-string piped to ConvertFrom-Json
      4. xaml/inputXML.xaml embedded as $inputXML
      5. scripts/start.ps1 (the entry point; runs last)
    The output is pure ASCII so Windows PowerShell 5.1 reads it identically whether it came
    from a file or from Invoke-RestMethod.
.PARAMETER Owner
    GitHub account (or organization) that hosts the repository. Baked into the self-elevation
    URL unless -Url overrides it.
.PARAMETER Beta
    Build a private-beta script: the header grants no licence, the bottom bar and boot screen say
    so, and the script asks -StatusUrl at start-up and refuses to run unless the answer is "ok".
    The gate under gate/ stamps each served copy with the tester's key, so a leaked copy or
    one-liner identifies who leaked it. Public builds omit this and are never gated.
.PARAMETER Url
    Full URL the script re-downloads itself from when it self-elevates. Defaults to the raw
    GitHub URL for Owner/Repo/Branch; for a beta build the gate rewrites it per tester anyway.
.PARAMETER StatusUrl
    URL of the gate's status endpoint. Empty (the default) means the build is not gated.
.PARAMETER Run
    Run the compiled script afterwards (Windows only).
#>
[CmdletBinding()]
param(
    [string]$Owner  = 'unknownaimer',
    [string]$Repo   = 'unknownutility',
    [string]$Branch = 'main',
    [string]$Version = '0.0.67',
    [switch]$Beta,
    [string]$Url,
    [string]$StatusUrl,
    [string]$OutFile,
    [switch]$Run
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
# Windows PowerShell 5.1 leaves $PSScriptRoot empty inside a param() default on an advanced script,
# so the default output path is resolved here rather than in the parameter block.
if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot 'unknowntweaks.ps1' }

$version = $Version
if (-not $Url) { $Url = "https://raw.githubusercontent.com/$Owner/$Repo/$Branch/unknowntweaks.ps1" }
$rawUrl  = $Url
$nl = "`r`n"
$sb = New-Object System.Text.StringBuilder

function Add-Block([string]$text) { [void]$script:sb.Append($text.TrimEnd()).Append($nl).Append($nl) }

# A beta build must not carry the MIT grant: under MIT a leaked copy is not a leak, it is a
# permitted redistribution. The public build gets the licence back.
$tagLine     = 'unknowntweaks - free, open-source Windows gaming optimizer.'
$licenseLine = 'License : MIT (see LICENSE in the repository)'
$betaLiteral = '$false'
if ($Beta) {
    $tagLine     = 'unknowntweaks - PRIVATE BETA build.'
    $licenseLine = 'License : none granted. Private beta, all rights reserved. Do not share this file or your one-liner.'
    $betaLiteral = '$true'
}
if ($StatusUrl -and -not $Beta) { throw 'A -StatusUrl only makes sense with -Beta.' }

# 1. header
Add-Block @"
<#
    $tagLine
    Version : $version
    Source  : https://github.com/$Owner/$Repo
    $licenseLine

    This file is GENERATED by Compile.ps1. Edit the files under functions/, config/, xaml/
    and scripts/ instead, then rebuild.
#>

`$sync = [Hashtable]::Synchronized(@{})
`$sync.version    = '$version'
`$sync.url        = '$rawUrl'
`$sync.repo       = 'https://github.com/$Owner/$Repo'
`$sync.beta       = $betaLiteral
`$sync.statusUrl  = '$StatusUrl'
`$sync.betaTester = ''
`$sync.configs    = @{}
"@

# 2. functions (private first so helpers exist before callers; stable order for diffs)
$functionFiles = @(Get-ChildItem -Path (Join-Path $PSScriptRoot 'functions') -Recurse -Filter *.ps1 -File |
    Sort-Object { $_.DirectoryName -notmatch 'private' }, FullName)
foreach ($f in $functionFiles) {
    Add-Block ("#region {0}{1}{2}{1}#endregion" -f $f.Name, $nl, (Get-Content -Raw -LiteralPath $f.FullName))
}

# 3. configs
foreach ($j in (Get-ChildItem -Path (Join-Path $PSScriptRoot 'config') -Filter *.json -File | Sort-Object Name)) {
    $raw = Get-Content -Raw -LiteralPath $j.FullName
    if ($raw -match "(?m)^'@") { throw "config/$($j.Name): a line starts with '@ which would terminate the here-string" }
    # parse once here so a broken file fails the build, not the user's machine
    $null = $raw | ConvertFrom-Json
    Add-Block ("`$sync.configs.{0} = @'{1}{2}{1}'@ | ConvertFrom-Json" -f $j.BaseName, $nl, $raw.TrimEnd())
}

# 4. xaml
$xamlPath = Join-Path $PSScriptRoot 'xaml\inputXML.xaml'
$xaml = Get-Content -Raw -LiteralPath $xamlPath
if ($xaml -match "(?m)^'@") { throw "xaml/inputXML.xaml: a line starts with '@" }
$null = [xml]$xaml
Add-Block ("`$inputXML = @'{0}{1}{0}'@" -f $nl, $xaml.TrimEnd())

# 5. entry point
Add-Block (Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'scripts\start.ps1'))

$text = $sb.ToString()

# ASCII guard: 5.1 reads BOM-less files as ANSI, and a BOM is unwelcome when piped through iex.
$nonAscii = [regex]::Matches($text, '[^\x00-\x7F]')
if ($nonAscii.Count) {
    $sample = ($nonAscii | Select-Object -First 5 | ForEach-Object { 'U+{0:X4}' -f [int][char]$_.Value }) -join ', '
    throw "Compiled output contains $($nonAscii.Count) non-ASCII character(s) ($sample). Use XAML entities like &#x25B6; or plain ASCII."
}

[System.IO.File]::WriteAllText($OutFile, $text, [System.Text.Encoding]::ASCII)
Write-Host ("Built {0} ({1:N0} bytes, version {2}, {3} functions, url {4})" -f $OutFile, $text.Length, $version, $functionFiles.Count, $rawUrl)

if ($Run) { & $OutFile }
